### ISSUE TITLE
Doesn't inject just crashes

### ISSUE THREAD

**Issue by bakill3** [ThaisenPM/Loader2#29]
I really like your work changed all you said in the readme, done the Cheat-Loader-CSGO-1.0 and it worked but this one just doesn't. I can login and when i press inject develepor or admin it says waiting for cs:go and then it just crashes

**Comment by bakill3** [comment]
fixed it changed it a bit:
Form3:

 var injectorcaralho = new ManualMapInjector(target) { AsyncInjection = true };
                    label1.Text = $"hmodule = 0x{injectorcaralho.Inject(file).ToInt64():x8}";
                    label1.Text = "Successfully injected";
                    File.Delete("C:\\Temp\\cheat.dll");
                    Application.Exit();
                    timer1.Stop();
                    timer2.Start();


//File.Delete("C:\\Temp\\cheat.dll");
            //Application.Exit();


Form1:

 private void Form1_Load(object sender, EventArgs e)
        {

            metroCheckBox1.Checked = true;

            var steam = "steam";
            var starget = Process.GetProcessesByName(steam).FirstOrDefault();

            hwidstring = HWDI.GetMachineGuid();

            metroTextBox1.Text = Properties.Settings.Default.Username;
            metroTextBox2.Text = Properties.Settings.Default.Password;

            Process[] pname = Process.GetProcessesByName("steam");
            if (pname.Length != 0)
            {
                MessageBox.Show("Close steam and then open cheats");
                Application.Exit();
            }

        }

**Comment by ThaisenPM** [comment]
Most likely an issue with your DLL. Injection method is working 100%
