### ISSUE TITLE
PtrToStructure

### ISSUE THREAD

**Issue by Exile69** [ThaisenPM/Loader2#34]
Any Idea i need a quick reply.

**Comment by ThaisenPM** [comment]
Great explanation... bye

**Comment by pityc** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0308	The non-generic method 'Marshal.PtrToStructure(IntPtr, object)' cannot be used with type arguments	MetroLoader	D:\ALTU\LoreCheat\Loader2-master\MetroLoader\MetroLoader\Injection\Win32\Imports.cs	158	Active

**Comment by RouterRage** [comment]
That didn't explain shit either.

**Comment by pityc** [comment]
I solve it...it was an error from net framework 4.6.1
