### ISSUE TITLE
ProToStructure

### ISSUE THREAD

**Issue by pityc** [ThaisenPM/Loader2#35]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0308	The non-generic method 'Marshal.PtrToStructure(IntPtr, object)' cannot be used with type arguments	MetroLoader	D:\Loader2-master\MetroLoader\MetroLoader\Injection\Win32\Imports.cs	158	Active

**Comment by Zaczero** [comment]
I had similar problem in the past. Just update your .NET Framework to the newer one. I use 4.5.2 and everything works fine 👍
