### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by proxendev** [ThaisenPM/Loader2#39]
How to change name of MetroFramework.dll?

**Comment by JamesShengKing** [comment]
Help! How do you change the passwords and the usernames PLZZ HELP

**Comment by JamesShengKing** [comment]
PLZZZZZ HELP MEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by DanielK1511** [comment]
@JamesShengKing Stop spamming, it wont make anyone respond faster.

**Comment by kodaLee** [comment]
I know I'm late but you can use Costura.Fody.
