### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by sndcode** [ThaisenPM/Loader2#45]
Without looking too deep into this, what are you doing agains sniffing the DLL with Fiddler ? 
Or how to make sure you cannot edit the exe with DnSpy to patch out the login check ?
Basically you can debug the assembly and breakpoint out the exact dll file too

**Comment by SleekZ** [comment]
This is really just a basic, template with bare bone security so don't expect to make a successful p2c out of this.

**Comment by sndcode** [comment]
> This is really just a basic, template with bare bone security so don't expect to make a successful p2c out of this.

I wont make anything out of it , i was just curious since you said you sold this stuff .
But theoretically one could just make the actual cheat depending to work if the user is valid and server sends back correct offsets .
